# Generated by Django 4.2.30 on 2026-07-11 23:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('lien', models.URLField(blank=True, verbose_name='Lien (optionnel)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Début d'affichage")),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'affichage")),
            ],
            options={
                'verbose_name': 'Annonce (bandeau)',
                'verbose_name_plural': 'Annonces (bandeau)',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PhotoSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, max_length=150, verbose_name='Légende (optionnelle)')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ajoutée le')),
            ],
            options={
                'verbose_name': 'Photo de la salle (galerie)',
                'verbose_name_plural': 'Photos de la salle (galerie)',
                'ordering': ['ordre_affichage', '-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='T-GYM', max_length=100, verbose_name='Nom de la salle')),
                ('slogan', models.CharField(default='La référence du sport.', max_length=200, verbose_name='Slogan')),
                ('horaires_texte', models.CharField(default='Ouvert 7j/7 (du Lundi au Dimanche) de 07h00 à 21h00', max_length=150, verbose_name='Horaires (affichage)')),
                ('whatsapp_numero_1', models.CharField(default='94140535', max_length=20, verbose_name='Numéro WhatsApp #1')),
                ('whatsapp_numero_2', models.CharField(default='63404995', max_length=20, verbose_name='Numéro WhatsApp #2')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/tgymbenin', verbose_name='Lien page Facebook')),
                ('instagram_url', models.URLField(blank=True, default='', verbose_name='Lien page Instagram')),
                ('adresse_zone', models.CharField(default='Abomey-Calavi, tronçon Carrefour TOKAN - Carrefour HOUÈTÔ', max_length=150, verbose_name='Zone')),
                ('adresse_reperes', models.CharField(default='À gauche en quittant le carrefour Tokan, ou à droite en quittant le carrefour Houètô.', max_length=255, verbose_name='Repères de direction')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, help_text="Ex: 6.4483. Laisser vide si inconnu — le lien Maps utilisera l'adresse texte à la place.", max_digits=10, null=True, verbose_name='Latitude GPS')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, help_text='Ex: 2.3548', max_digits=10, null=True, verbose_name='Longitude GPS')),
                ('hero_image', models.ImageField(blank=True, help_text="Photo large de la salle affichée derrière le titre de l'accueil. Idéalement une photo prise en salle, ambiance/lumière (1600px de large minimum).", null=True, upload_to='site/', verbose_name='Photo de fond (accueil)')),
                ('hero_video', models.FileField(blank=True, help_text="Courte vidéo (10-20s, en boucle, sans son) de l'ambiance de la salle. Si renseignée, prend le pas sur la photo de fond. Fichier léger recommandé (<10 Mo).", null=True, upload_to='site/', verbose_name='Vidéo de fond (accueil, optionnel)')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='VideoSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text='Format vertical ou horizontal, les deux fonctionnent. Fichier léger recommandé (idéalement <15 Mo, sans son nécessaire — elle sera lue en muet/boucle, sauf en carrousel témoignages où le son est utilisé).', upload_to='videos/', verbose_name='Fichier vidéo')),
                ('apercu', models.ImageField(blank=True, help_text='Image affichée le temps que la vidéo charge. Optionnelle mais recommandée.', null=True, upload_to='videos/apercus/', verbose_name="Image d'aperçu (poster)")),
                ('legende', models.CharField(blank=True, max_length=150, verbose_name='Légende (optionnelle)')),
                ('type_video', models.CharField(choices=[('generale', 'Généraliste (pas de programme)'), ('activite', 'Activité (programme)'), ('temoignage', 'Témoignage (programme)')], default='generale', help_text="Ignoré si aucun programme n'est renseigné (repasse automatiquement à 'Généraliste' à l'enregistrement dans ce cas).", max_length=20, verbose_name='Type')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ajoutée le')),
                ('programme', models.ForeignKey(blank=True, help_text='Laisser vide pour une vidéo généraliste (mur accueil + tarifs). Renseigner pour une vidéo liée à un programme (voir le champ Type).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='coaching.programme', verbose_name='Programme associé (optionnel)')),
            ],
            options={
                'verbose_name': 'Vidéo de la salle',
                'verbose_name_plural': 'Vidéos de la salle',
                'ordering': ['ordre_affichage', '-date_ajout'],
            },
        ),
    ]
