# Generated by Django 6.0.6 on 2026-07-02 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Message')),
                ('lien', models.URLField(blank=True, verbose_name='Lien (optionnel)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Début d'affichage")),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name="Fin d'affichage")),
            ],
            options={
                'verbose_name': 'Annonce (bandeau)',
                'verbose_name_plural': 'Annonces (bandeau)',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='T-GYM', max_length=100, verbose_name='Nom de la salle')),
                ('slogan', models.CharField(default='La référence du sport.', max_length=200, verbose_name='Slogan')),
                ('horaires_texte', models.CharField(default='Ouvert 7j/7 (du Lundi au Dimanche) de 07h00 à 21h00', max_length=150, verbose_name='Horaires (affichage)')),
                ('whatsapp_numero_1', models.CharField(default='94140535', max_length=20, verbose_name='Numéro WhatsApp #1')),
                ('whatsapp_numero_2', models.CharField(default='63404995', max_length=20, verbose_name='Numéro WhatsApp #2')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/tgymbenin', verbose_name='Lien page Facebook')),
                ('adresse_zone', models.CharField(default='Abomey-Calavi, tronçon Carrefour TOKAN - Carrefour HOUÈTÔ', max_length=150, verbose_name='Zone')),
                ('adresse_reperes', models.CharField(default='À gauche en quittant le carrefour Tokan, ou à droite en quittant le carrefour Houètô.', max_length=255, verbose_name='Repères de direction')),
                ('google_maps_embed_url', models.URLField(blank=True, verbose_name='URL embed Google Maps')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
