# Generated by Django 6.0.6 on 2026-07-03 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='google_maps_embed_url',
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Ex: 6.4483. Laisser vide si inconnu — le lien Maps utilisera l'adresse texte à la place.", max_digits=10, null=True, verbose_name='Latitude GPS'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Ex: 2.3548', max_digits=10, null=True, verbose_name='Longitude GPS'),
        ),
    ]
