# Generated by Django 4.2.30 on 2026-07-12 00:37

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hero_video',
            field=models.FileField(blank=True, help_text="Courte vidéo (10-20s, en boucle, sans son) de l'ambiance de la salle. Si renseignée, prend le pas sur la photo de fond. Fichier léger recommandé (<10 Mo).", null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='video'), upload_to='site/', verbose_name='Vidéo de fond (accueil, optionnel)'),
        ),
        migrations.AlterField(
            model_name='videosalle',
            name='fichier',
            field=models.FileField(help_text='Format vertical ou horizontal, les deux fonctionnent. Fichier léger recommandé (idéalement <15 Mo, sans son nécessaire — elle sera lue en muet/boucle, sauf en carrousel témoignages où le son est utilisé).', storage=cloudinary_storage.storage.MediaCloudinaryStorage(resource_type='video'), upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
    ]
