# Generated by Django 4.2.30 on 2026-07-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_siteconfig_google_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/tgymbenin/', verbose_name='Lien page Instagram'),
        ),
    ]
