# Generated by Django 4.2.30 on 2026-07-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_siteconfig_hero_video_alter_videosalle_fichier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosalle',
            name='type_video',
            field=models.CharField(choices=[('generale', 'Généraliste (pas de programme)'), ('activite', 'Activité (programme)'), ('temoignage', 'Révélation (programme)')], default='generale', help_text="Ignoré si aucun programme n'est renseigné (repasse automatiquement à 'Généraliste' à l'enregistrement dans ce cas).", max_length=20, verbose_name='Type'),
        ),
    ]
