# Generated by Django 4.2.30 on 2026-07-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_instagram_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='instagram_url',
        ),
    ]
