# Generated by Django 4.2.30 on 2026-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_videosalle_type_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='faq_contexte',
            field=models.TextField(blank=True, default='', help_text="Réponses aux questions récurrentes des clients — essai gratuit possible, moyens de paiement acceptés, gel/pause d'abonnement, remboursement, règles d'accès, tenue requise, etc. Texte libre (une question/réponse par ligne, ou paragraphes), injecté tel quel dans le contexte du chatbot WhatsApp/site : c'est la source la plus directe pour éviter qu'il ne réponde à côté ou escalade vers un humain sur des questions basiques déjà répondues ici.", verbose_name="FAQ / politiques (pour l'assistant IA)"),
        ),
    ]
