# Generated by Django 4.2.30 on 2026-07-03 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_siteconfig_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='instagram_url',
            field=models.URLField(blank=True, default='', verbose_name='Lien page Instagram'),
        ),
    ]
