# Generated by Django 4.2.30 on 2026-07-10 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
        ('core', '0005_siteconfig_instagram_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galerie/', verbose_name='Photo')),
                ('legende', models.CharField(blank=True, max_length=150, verbose_name='Légende (optionnelle)')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ajoutée le')),
            ],
            options={
                'verbose_name': 'Photo de la salle (galerie)',
                'verbose_name_plural': 'Photos de la salle (galerie)',
                'ordering': ['ordre_affichage', '-date_ajout'],
            },
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_image',
            field=models.ImageField(blank=True, help_text="Photo large de la salle affichée derrière le titre de l'accueil. Idéalement une photo prise en salle, ambiance/lumière (1600px de large minimum).", null=True, upload_to='site/', verbose_name='Photo de fond (accueil)'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_video',
            field=models.FileField(blank=True, help_text="Courte vidéo (10-20s, en boucle, sans son) de l'ambiance de la salle. Si renseignée, prend le pas sur la photo de fond. Fichier léger recommandé (<10 Mo).", null=True, upload_to='site/', verbose_name='Vidéo de fond (accueil, optionnel)'),
        ),
        migrations.CreateModel(
            name='VideoSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text='Format vertical ou horizontal, les deux fonctionnent. Fichier léger recommandé (idéalement <15 Mo, sans son nécessaire — elle sera lue en muet/boucle).', upload_to='videos/', verbose_name='Fichier vidéo')),
                ('apercu', models.ImageField(blank=True, help_text='Image affichée le temps que la vidéo charge. Optionnelle mais recommandée.', null=True, upload_to='videos/apercus/', verbose_name="Image d'aperçu (poster)")),
                ('legende', models.CharField(blank=True, max_length=150, verbose_name='Légende (optionnelle)')),
                ('actif', models.BooleanField(default=True, verbose_name='Visible sur le site')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ajoutée le')),
                ('programme', models.ForeignKey(blank=True, help_text='Si renseigné, cette vidéo apparaît dans la section du programme phare plutôt que dans le mur vidéo général.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='coaching.programme', verbose_name='Programme associé (optionnel)')),
            ],
            options={
                'verbose_name': 'Vidéo de la salle',
                'verbose_name_plural': 'Vidéos de la salle',
                'ordering': ['ordre_affichage', '-date_ajout'],
            },
        ),
    ]
