# Generated by Django 4.2.30 on 2026-07-11 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
        ('core', '0006_photosalle_siteconfig_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosalle',
            name='type_video',
            field=models.CharField(choices=[('generale', 'Généraliste (pas de programme)'), ('activite', 'Activité (programme)'), ('temoignage', 'Témoignage (programme)')], default='generale', help_text="Ignoré si aucun programme n'est renseigné (repasse automatiquement à 'Généraliste' à l'enregistrement dans ce cas).", max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='videosalle',
            name='fichier',
            field=models.FileField(help_text='Format vertical ou horizontal, les deux fonctionnent. Fichier léger recommandé (idéalement <15 Mo, sans son nécessaire — elle sera lue en muet/boucle, sauf en carrousel témoignages où le son est utilisé).', upload_to='videos/', verbose_name='Fichier vidéo'),
        ),
        migrations.AlterField(
            model_name='videosalle',
            name='programme',
            field=models.ForeignKey(blank=True, help_text='Laisser vide pour une vidéo généraliste (mur accueil + tarifs). Renseigner pour une vidéo liée à un programme (voir le champ Type).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='coaching.programme', verbose_name='Programme associé (optionnel)'),
        ),
    ]
