# Generated by Django 6.0.6 on 2026-07-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug (URL)')),
                ('accroche', models.CharField(help_text='Ex: Un accompagnement intensif pour des résultats visibles et durables.', max_length=200, verbose_name='Accroche courte')),
                ('duree', models.CharField(help_text='Ex: 45 jours', max_length=50, verbose_name='Durée')),
                ('objectif', models.TextField(help_text="Ce que le programme vise à obtenir pour l'adhérent.", verbose_name='Objectif')),
                ('inclus', models.JSONField(blank=True, default=list, help_text="Liste de points (ex: ['Suivi coach quotidien', 'Plan nutritionnel dédié'])", verbose_name='Ce qui est inclus')),
                ('prix_fcfa', models.PositiveIntegerField(blank=True, help_text='Laisser vide si inclus dans un abonnement existant.', null=True, verbose_name='Prix (FCFA)')),
                ('prix_note', models.CharField(blank=True, help_text="Ex: 'Inclus dans l'abonnement Premium' ou 'Tarif dédié, hors abonnement'", max_length=150, verbose_name='Précision tarif')),
                ('est_phare', models.BooleanField(default=False, help_text="Mis en avant sur la page d'accueil et la méthode.", verbose_name='Programme phare')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (visible sur le site)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'ordering': ['ordre_affichage', 'titre'],
            },
        ),
    ]
