# Generated by Django 4.2.30 on 2026-07-11 23:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=datetime.date.today, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Calculée automatiquement si la formule a une durée définie (écrase la saisie manuelle à chaque enregistrement). Sinon, à renseigner à la main.', null=True, verbose_name='Date de fin')),
                ('actif', models.BooleanField(default=True, help_text='Décoche pour clore/annuler cet abonnement sans le supprimer.', verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_debut', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la formule')),
                ('categorie', models.CharField(choices=[('premium', 'Abonnement Standard (Premium)'), ('flexible', 'Formule flexible (à la carte)')], default='flexible', max_length=20, verbose_name='Catégorie')),
                ('prix_fcfa', models.PositiveIntegerField(verbose_name='Prix (FCFA)')),
                ('periode', models.CharField(help_text='Ex: /mois, pour 14 séances/mois, /semaine', max_length=50, verbose_name='Période')),
                ('duree_jours', models.PositiveIntegerField(blank=True, help_text="Utilisée pour calculer automatiquement la date de fin d'un abonnement (ex: 30 pour un mensuel). Laisser vide pour les formules sans durée calculable (ex: à la carte) — la date de fin restera alors saisie manuellement.", null=True, verbose_name='Durée (jours)')),
                ('description_courte', models.CharField(blank=True, help_text="Ex: '14 séances dans le mois'", max_length=150, verbose_name='Description courte')),
                ('inclus', models.JSONField(blank=True, default=list, help_text="Liste de points affichés sous forme de checklist (ex: ['Accès salle', 'Suivi coach permanent'])", verbose_name='Éléments inclus')),
                ('is_populaire', models.BooleanField(default=False, help_text='Affiche cette formule comme le choix recommandé sur la grille tarifaire.', verbose_name='Mettre en avant')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (visible sur le site)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Formule tarifaire',
                'verbose_name_plural': 'Formules tarifaires',
                'ordering': ['ordre_affichage', 'prix_fcfa'],
            },
        ),
        migrations.CreateModel(
            name='RelanceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expiration_ciblee', models.DateField(help_text="Copie de la date de fin de l'abonnement au moment de la génération — sert à éviter de régénérer un message pour la même échéance.", verbose_name="Date d'expiration ciblée")),
                ('contenu', models.TextField(verbose_name='Message généré')),
                ('genere_par_ia', models.BooleanField(default=True, help_text="Décoché si l'IA était indisponible au moment de la génération et qu'un message de secours (gabarit fixe) a été utilisé à la place.", verbose_name="Généré par l'IA")),
                ('statut', models.CharField(choices=[('a_envoyer', 'À envoyer (copier manuellement)'), ('envoye', 'Envoyé'), ('ignore', 'Ignoré')], default='a_envoyer', max_length=20, verbose_name='Statut')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('envoye_automatiquement', models.BooleanField(default=False, help_text="Coché si envoyé via l'API WhatsApp Business (Étape 4), décoché si envoyé/à envoyer manuellement par le staff.", verbose_name='Envoyé automatiquement')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='abonnements.abonnement', verbose_name='Abonnement')),
                ('envoye_par', models.ForeignKey(blank=True, help_text="Membre du staff qui a envoyé le message manuellement. Vide si l'envoi a été automatique (voir « Envoyé automatiquement »).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': 'Message de relance',
                'verbose_name_plural': 'Messages de relance',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.AddField(
            model_name='abonnement',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='abonnements.plan', verbose_name='Formule'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL, verbose_name='Adhérent'),
        ),
    ]
