# Generated by Django 6.0.6 on 2026-07-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la formule')),
                ('categorie', models.CharField(choices=[('premium', 'Abonnement Standard (Premium)'), ('flexible', 'Formule flexible (à la carte)')], default='flexible', max_length=20, verbose_name='Catégorie')),
                ('prix_fcfa', models.PositiveIntegerField(verbose_name='Prix (FCFA)')),
                ('periode', models.CharField(help_text='Ex: /mois, pour 14 séances/mois, /semaine', max_length=50, verbose_name='Période')),
                ('description_courte', models.CharField(blank=True, help_text="Ex: '14 séances dans le mois'", max_length=150, verbose_name='Description courte')),
                ('inclus', models.JSONField(blank=True, default=list, help_text="Liste de points affichés sous forme de checklist (ex: ['Accès salle', 'Suivi coach permanent'])", verbose_name='Éléments inclus')),
                ('is_populaire', models.BooleanField(default=False, help_text='Affiche cette formule comme le choix recommandé sur la grille tarifaire.', verbose_name='Mettre en avant')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (visible sur le site)')),
                ('ordre_affichage', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Formule tarifaire',
                'verbose_name_plural': 'Formules tarifaires',
                'ordering': ['ordre_affichage', 'prix_fcfa'],
            },
        ),
    ]
