# Generated by Django 4.2.30 on 2026-07-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text="Numéro au format international sans '+', ex: 22997393766", max_length=20, unique=True, verbose_name='Numéro WhatsApp (wa_id)')),
                ('nom_contact', models.CharField(blank=True, help_text='Renseigné automatiquement depuis le profil WhatsApp si disponible.', max_length=150, verbose_name='Nom du contact')),
                ('derniere_activite', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('abonnement', models.ForeignKey(blank=True, help_text='Rapproché manuellement si besoin — aucun lien automatique par défaut.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_whatsapp', to='abonnements.abonnement', verbose_name='Abonnement lié')),
            ],
            options={
                'verbose_name': 'Conversation WhatsApp',
                'verbose_name_plural': 'Conversations WhatsApp',
                'ordering': ['-derniere_activite'],
            },
        ),
        migrations.CreateModel(
            name='MessageWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sens', models.CharField(choices=[('entrant', 'Reçu du client'), ('sortant', 'Envoyé par T GYM')], max_length=10, verbose_name='Sens')),
                ('wamid', models.CharField(blank=True, help_text='Identifiant Meta du message — sert à éviter les doublons sur retry webhook.', max_length=150, null=True, unique=True, verbose_name='ID message (wamid)')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('categorie', models.CharField(choices=[('session', 'Message libre (session 24h)'), ('marketing', 'Template Marketing'), ('utility', 'Template Utility'), ('authentication', 'Template Authentication')], default='session', max_length=20, verbose_name='Catégorie')),
                ('est_facturable', models.BooleanField(default=False, help_text='Coché si ce message correspond à un envoi facturé selon les règles Meta en vigueur (template hors fenêtre de service).', verbose_name='Facturé par Meta')),
                ('statut_livraison', models.CharField(blank=True, help_text="sent / delivered / read / failed — mis à jour via les webhooks 'statuses'.", max_length=20, verbose_name='Statut de livraison')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('payload_brut', models.JSONField(blank=True, help_text='Copie du payload webhook Meta pour ce message, utile pour du débug.', null=True, verbose_name='Payload brut')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='abonnements.conversationwhatsapp', verbose_name='Conversation')),
            ],
            options={
                'verbose_name': 'Message WhatsApp',
                'verbose_name_plural': 'Messages WhatsApp',
                'ordering': ['date_envoi'],
            },
        ),
    ]
