# Generated by Django 4.2.30 on 2026-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_conversationwhatsapp_messagewhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('telephone', models.CharField(help_text='Format international, ex: 22997393766 ou +22997393766.', max_length=20, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, help_text='Décoche pour exclure ce contact des prochains envois en masse sans le supprimer.', verbose_name='Actif')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Note')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
            ],
            options={
                'verbose_name': 'Contact (envoi de masse)',
                'verbose_name_plural': 'Contacts (envoi de masse)',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TemplateWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(help_text='Ex: Promo rentrée, Relance abonnement...', max_length=100, unique=True, verbose_name='Intitulé (affiché au staff)')),
                ('nom_meta', models.CharField(help_text='Doit correspondre EXACTEMENT au nom du template approuvé dans le dashboard Meta.', max_length=100, verbose_name='Nom technique du template (Meta)')),
                ('langue', models.CharField(default='fr', max_length=10, verbose_name='Code langue')),
                ('variables', models.JSONField(blank=True, default=list, help_text='Liste des noms de variables dans l\'ordre {{1}}, {{2}}... Ex: ["prenom", "nom_promo"]. Laisser vide si le template n\'a pas de variable.', verbose_name="Variables du corps, dans l'ordre")),
                ('actif', models.BooleanField(default=True, verbose_name='Actif (proposé dans la diffusion)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Template WhatsApp',
                'verbose_name_plural': 'Templates WhatsApp',
                'ordering': ['intitule'],
            },
        ),
        migrations.AddField(
            model_name='conversationwhatsapp',
            name='mode_bot',
            field=models.CharField(choices=[('bot', 'Gemini répond automatiquement'), ('humain', 'Escaladé — réponse humaine requise')], default='bot', help_text="Passe automatiquement en 'Humain' si le client se montre insatisfait ou si Gemini ne sait pas répondre. Remets sur 'Bot' une fois la situation gérée.", max_length=10, verbose_name='Mode de réponse'),
        ),
        migrations.AddField(
            model_name='conversationwhatsapp',
            name='raison_escalade',
            field=models.CharField(blank=True, max_length=255, verbose_name="Raison de l'escalade"),
        ),
    ]
