# Generated by Django 4.2.30 on 2026-07-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0002_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duree_jours',
            field=models.PositiveIntegerField(blank=True, help_text="Utilisée pour calculer automatiquement la date de fin d'un abonnement (ex: 30 pour un mensuel). Laisser vide pour les formules sans durée calculable (ex: à la carte) — la date de fin restera alors saisie manuellement.", null=True, verbose_name='Durée (jours)'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='date_fin',
            field=models.DateField(blank=True, help_text='Calculée automatiquement si la formule a une durée définie (écrase la saisie manuelle à chaque enregistrement). Sinon, à renseigner à la main.', null=True, verbose_name='Date de fin'),
        ),
    ]
