# Generated by Django 4.2.30 on 2026-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0003_contactmasse_templatewhatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatewhatsapp',
            name='categorie',
            field=models.CharField(choices=[('session', 'Message libre (session 24h)'), ('marketing', 'Template Marketing'), ('utility', 'Template Utility'), ('authentication', 'Template Authentication')], default='marketing', help_text='Doit correspondre à la catégorie approuvée sur Meta (Marketing/Utility/Authentication) — utilisée pour un suivi correct de la facturation dans les conversations.', max_length=20, verbose_name='Catégorie Meta'),
        ),
    ]
