# Generated by Django 4.2.30 on 2026-07-08 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abonnements', '0003_plan_duree_jours_alter_abonnement_date_fin'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelanceMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expiration_ciblee', models.DateField(help_text="Copie de la date de fin de l'abonnement au moment de la génération — sert à éviter de régénérer un message pour la même échéance.", verbose_name="Date d'expiration ciblée")),
                ('contenu', models.TextField(verbose_name='Message généré')),
                ('genere_par_ia', models.BooleanField(default=True, help_text="Décoché si l'IA était indisponible au moment de la génération et qu'un message de secours (gabarit fixe) a été utilisé à la place.", verbose_name="Généré par l'IA")),
                ('statut', models.CharField(choices=[('a_envoyer', 'À envoyer (copier manuellement)'), ('envoye', 'Envoyé'), ('ignore', 'Ignoré')], default='a_envoyer', max_length=20, verbose_name='Statut')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relances', to='abonnements.abonnement', verbose_name='Abonnement')),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': 'Message de relance',
                'verbose_name_plural': 'Messages de relance',
                'ordering': ['-date_generation'],
            },
        ),
    ]
