# Generated by Django 4.2.30 on 2026-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnements', '0004_templatewhatsapp_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagewhatsapp',
            name='media_url',
            field=models.URLField(blank=True, default='', help_text='URL Cloudinary permanente du média reçu — les URLs fournies par Meta pour télécharger un média expirent au bout de 5 minutes, donc on le retélécharge et le réhéberge une seule fois à la réception.', verbose_name='Média (image/audio/document)'),
        ),
    ]
