# Generated by Django 4.2.30 on 2026-07-08 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abonnements', '0004_relancemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='relancemessage',
            name='envoye_automatiquement',
            field=models.BooleanField(default=False, help_text="Coché si envoyé via l'API WhatsApp Business (Étape 4), décoché si envoyé/à envoyer manuellement par le staff.", verbose_name='Envoyé automatiquement'),
        ),
        migrations.AlterField(
            model_name='relancemessage',
            name='envoye_par',
            field=models.ForeignKey(blank=True, help_text="Membre du staff qui a envoyé le message manuellement. Vide si l'envoi a été automatique (voir « Envoyé automatiquement »).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relances_envoyees', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par'),
        ),
    ]
