# Generated by Django 4.2.30 on 2026-07-11 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('staff', 'Staff (admin salle)'), ('coach', 'Coach'), ('adherent', 'Adhérent')], default='adherent', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, help_text='Numéro local (ex: 94140535), utilisé pour le contact/relance WhatsApp.', max_length=20, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
                'ordering': ['user__username'],
            },
        ),
    ]
