# Generated by Django 4.2.30 on 2026-07-11 23:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True, verbose_name='Slug (URL)')),
                ('categorie', models.CharField(choices=[('conseil', 'Conseil'), ('evenement', 'Événement'), ('resultat', "Résultat d'adhérent"), ('actu_salle', 'Actu de la salle')], default='conseil', max_length=20, verbose_name='Catégorie')),
                ('accroche', models.CharField(help_text="Résumé affiché dans la liste, avant l'ouverture de l'article.", max_length=200, verbose_name='Accroche courte')),
                ('corps', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, help_text="Optionnelle. Laisser vide si pas d'image.", null=True, upload_to='actualites/', verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False, help_text="Alimente le bandeau 'Top Body News' affiché sur tout le site.", verbose_name='Mise en avant (Top Body News)')),
                ('est_publiee', models.BooleanField(default=True, verbose_name='Publiée (visible sur le site)')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
